### PR TITLE
Fix default IP Address for BBB / Pumpkin MBM2

### PR DESCRIPTION
**Pull request by Psykar**
Docs updated at https://github.com/kubostech/kubos/pull/220

Default IP clashes with public IP ranges.

### CODE REVIEW

**Comment by CatGarab** [comment]
It's actually not a typo. I wanted an IP address that would be separate from my computer's normal network address, that way there wouldn't be any collisions or odd behaviors. It's a pretty arbitrary address, though, so if you having feelings about it, I'm open to ideas.

**Comment by Psykar** [comment]
Should probably be at least in a private IP range.
The 168.0.0.0 IP range is actually public, so setting a local interface to use that IP potentially blocks some internet access from your workstation *shrug.

I personally like the 10.0.0.0/8 private IP range for purely aesthetic reasons, but if you want one that's less likely to be used by people, the 172.16.0.0/12 seems the least used in my experience.

https://en.wikipedia.org/wiki/Private_network#Private_IPv4_address_spaces

At the same time, not a big deal, can just change it myself :)

**Comment by CatGarab** [comment]
`10.0.0.0/8` sounds good to me. You'll just need to create a second PR against the kubostech/kubos repo to update the docs (should be in the 'Working with the BBB' and 'Working with the MBM2' guides)

**Comment by Psykar** [comment]
Updated. And updated docs at https://github.com/kubostech/kubos/pull/220

**Pull request merged**
